# Generated by Django 5.2.4 on 2026-01-04 05:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence_id', models.CharField(max_length=100, unique=True)),
                ('case_number', models.CharField(max_length=100)),
                ('filename', models.CharField(max_length=255)),
                ('owner_email', models.EmailField(max_length=254)),
                ('original_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustodyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('performed_by', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('previous_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('current_hash', models.CharField(max_length=64)),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='COC.evidence')),
            ],
        ),
    ]
