# Generated by Django 5.2.4 on 2026-01-04 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0010_evidencedetails_court_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evidencedetails',
            name='court_otp',
        ),
    ]
