# Generated by Django 5.2.4 on 2026-02-18 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0011_remove_evidencedetails_court_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='reset_otp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
